#!/usr/bin/env bun
/**
 * Protocol codegen tool.
 *
 * Generates TypeScript interfaces, Swift structs, and Kotlin data classes
 * from Zod schemas (via toJSONSchema()) defined in apps/worker/schemas/.
 * Also generates crypto label constants.
 *
 * Usage:
 *   bun run codegen           # Generate all platform types
 */

import {
  quicktype,
  InputData,
  JSONSchemaInput,
  JSONSchemaStore,
  type LanguageName,
} from 'quicktype-core'
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { getSchemaRegistry } from './schema-registry'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const GENERATED_DIR = resolve(__dirname, '../generated')
const CRYPTO_LABELS_FILE = resolve(__dirname, '../crypto-labels.json')

// No-op schema store — all schemas are self-contained (no $ref across files)
class InlineSchemaStore extends JSONSchemaStore {
  async fetch(_address: string) {
    return undefined
  }
}

// Generate types for a target language from all schemas
async function generateForLanguage(
  language: LanguageName,
  schemas: Array<{ name: string; schema: string }>,
  rendererOptions: Record<string, string> = {},
): Promise<string[]> {
  const store = new InlineSchemaStore()
  const schemaInput = new JSONSchemaInput(store)

  for (const { name, schema } of schemas) {
    await schemaInput.addSource({ name, schema })
  }

  const inputData = new InputData()
  inputData.addInput(schemaInput)

  const result = await quicktype({
    inputData,
    lang: language,
    rendererOptions,
  })

  return result.lines
}

// Generate Swift crypto labels
function generateSwiftCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'import Foundation',
    '',
    '/// Cryptographic domain separation labels for all llamenos crypto operations.',
    '/// Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    '/// uses a unique context string from this enum.',
    'enum CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    static let ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

// Generate Kotlin crypto labels
function generateKotlinCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'package org.llamenos.protocol',
    '',
    '/**',
    ' * Cryptographic domain separation labels for all llamenos crypto operations.',
    ' * Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    ' * uses a unique context string from this object.',
    ' */',
    'object CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    const val ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

// Generate TypeScript crypto labels
function generateTSCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`export const ${name} = '${value}'`)
  }
  lines.push('')
  return lines.join('\n')
}

async function main() {
  // Build schema registry from Zod schemas
  const registry = getSchemaRegistry()
  console.log(`Found ${registry.length} schemas from Zod registry`)

  // Convert registry entries to JSON strings for quicktype
  const allSchemas = registry.map(({ name, jsonSchema }) => ({
    name,
    schema: JSON.stringify(jsonSchema),
  }))

  // Read crypto labels
  const cryptoLabelsData = JSON.parse(readFileSync(CRYPTO_LABELS_FILE, 'utf-8'))
  const cryptoLabels = cryptoLabelsData.labels as Record<string, string>
  console.log(`Found ${Object.keys(cryptoLabels).length} crypto labels`)

  // Generate for all three languages
  const [tsLines, swiftLines, kotlinLines] = await Promise.all([
    generateForLanguage('typescript', allSchemas, {
      'just-types': 'true',
    }),
    generateForLanguage('swift', allSchemas, {
      'just-types': 'true',
      'struct-or-class': 'struct',
      'swift-5-support': 'true',
    }),
    generateForLanguage('kotlin', allSchemas, {
      'just-types': 'true',
      framework: 'kotlinx',
    }),
  ])

  const header = '// Auto-generated by packages/protocol/tools/codegen.ts\n// Do not edit manually.\n\n'

  const tsContent = header + tsLines.join('\n') + '\n'
  const swiftContent = header + swiftLines.join('\n') + '\n'
  const kotlinContent = header + kotlinLines.join('\n') + '\n'

  const tsCryptoContent = generateTSCryptoLabels(cryptoLabels)
  const swiftCryptoContent = generateSwiftCryptoLabels(cryptoLabels)
  const kotlinCryptoContent = generateKotlinCryptoLabels(cryptoLabels)

  // Write generated files
  for (const dir of ['typescript', 'swift', 'kotlin']) {
    mkdirSync(join(GENERATED_DIR, dir), { recursive: true })
  }

  writeFileSync(join(GENERATED_DIR, 'typescript', 'types.ts'), tsContent)
  writeFileSync(join(GENERATED_DIR, 'typescript', 'crypto-labels.ts'), tsCryptoContent)
  writeFileSync(join(GENERATED_DIR, 'swift', 'Types.swift'), swiftContent)
  writeFileSync(join(GENERATED_DIR, 'swift', 'CryptoLabels.swift'), swiftCryptoContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'Types.kt'), kotlinContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'CryptoLabels.kt'), kotlinCryptoContent)

  console.log('Generated:')
  console.log('  typescript/types.ts + crypto-labels.ts')
  console.log('  swift/Types.swift + CryptoLabels.swift')
  console.log('  kotlin/Types.kt + CryptoLabels.kt')
}

main()
