#!/usr/bin/env bash
set -euo pipefail

# ── Llamenos Docker Setup ──────────────────────────────────────────
#
# Generates required secrets and starts Llamenos with Docker Compose.
# The setup wizard in the browser creates the admin account — no
# additional tools (Bun, Node.js, etc.) are needed.
#
# Prerequisites: Docker (with Docker Compose), openssl
#
# Usage:
#   ./scripts/docker-setup.sh                                  # Local (HTTP)
#   ./scripts/docker-setup.sh --domain hotline.org --email a@b # Production (TLS)
#   ./scripts/docker-setup.sh --demo                           # Demo mode
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_DIR="$REPO_ROOT/deploy/docker"
ENV_FILE="$COMPOSE_DIR/.env"

# Defaults
DOMAIN="localhost"
DEMO_MODE=""
ACME_EMAIL=""
LOCAL_MODE=true

# ── Parse arguments ──────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case $1 in
    --demo)      DEMO_MODE="true"; shift ;;
    --domain)    DOMAIN="$2"; LOCAL_MODE=false; shift 2 ;;
    --email)     ACME_EMAIL="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "  --demo              Demo mode (pre-seeded data, one-click login)"
      echo "  --domain DOMAIN     Production domain (enables automatic TLS)"
      echo "  --email EMAIL       Email for Let's Encrypt certificates"
      echo ""
      echo "Examples:"
      echo "  $0                                     # http://localhost:8000"
      echo "  $0 --demo                              # http://localhost:8000 with demo data"
      echo "  $0 --domain hotline.org --email a@b    # https://hotline.org"
      exit 0 ;;
    *) echo "Unknown option: $1 (try --help)"; exit 1 ;;
  esac
done

# ── Preflight ────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "Error: Docker is not installed. See https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "Error: Docker Compose is not available. See https://docs.docker.com/compose/install/"
  exit 1
fi

if ! command -v openssl &>/dev/null; then
  echo "Error: openssl is required to generate secrets."
  exit 1
fi

if [[ ! -f "$COMPOSE_DIR/docker-compose.yml" ]]; then
  echo "Error: deploy/docker/docker-compose.yml not found. Run from the repo root."
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  read -rp "deploy/docker/.env already exists. Overwrite? [y/N] " confirm
  [[ "$confirm" =~ ^[yY]$ ]] || { echo "Aborted."; exit 0; }
fi

# ── Build compose command ────────────────────────────────────────

COMPOSE_FILES="-f $COMPOSE_DIR/docker-compose.yml"
if [[ "$LOCAL_MODE" == false ]]; then
  COMPOSE_FILES="$COMPOSE_FILES -f $COMPOSE_DIR/docker-compose.production.yml"
fi

# ── Generate .env ────────────────────────────────────────────────

echo "Generating secrets..."

CADDY_SITE_ADDRESS=""
HTTP_PORT=""
[[ "$LOCAL_MODE" == true ]] && CADDY_SITE_ADDRESS="http://localhost" && HTTP_PORT="8000"

ENVIRONMENT="production"
[[ "$DEMO_MODE" == "true" ]] && ENVIRONMENT="development"

cat > "$ENV_FILE" << EOF
# Generated by docker-setup.sh — $(date -u +"%Y-%m-%d %H:%M UTC")

PG_PASSWORD=$(openssl rand -base64 24)
HMAC_SECRET=$(openssl rand -hex 32)
STORAGE_ACCESS_KEY=$(openssl rand -base64 16)
STORAGE_SECRET_KEY=$(openssl rand -base64 24)
SERVER_NOSTR_SECRET=$(openssl rand -hex 32)

DOMAIN=${DOMAIN}
CADDY_SITE_ADDRESS=${CADDY_SITE_ADDRESS}
${HTTP_PORT:+HTTP_PORT=${HTTP_PORT}}
ACME_EMAIL=${ACME_EMAIL}

HOTLINE_NAME=Hotline
ENVIRONMENT=${ENVIRONMENT}
${DEMO_MODE:+DEMO_MODE=true}
EOF

echo "  Written to deploy/docker/.env"

# ── Build & start ────────────────────────────────────────────────

echo ""
echo "Building (first run may take a few minutes)..."
docker compose $COMPOSE_FILES build --quiet 2>&1 | tail -5

echo "Starting services..."
docker compose $COMPOSE_FILES up -d

# ── Wait for health ──────────────────────────────────────────────

echo -n "Waiting for app to start"
for _ in $(seq 1 40); do
  if curl -sf http://localhost:${HTTP_PORT:-80}/api/health &>/dev/null || curl -sf http://localhost:3000/api/health &>/dev/null; then
    echo " ready!"
    break
  fi
  echo -n "."
  sleep 3
done

# ── Done ─────────────────────────────────────────────────────────

if [[ "$LOCAL_MODE" == true ]]; then
  URL="http://localhost:8000"
  COMPOSE_CMD="docker compose -f deploy/docker/docker-compose.yml"
else
  URL="https://${DOMAIN}"
  COMPOSE_CMD="docker compose -f deploy/docker/docker-compose.yml -f deploy/docker/docker-compose.production.yml"
fi

echo ""
echo "====================================="
echo "  Llamenos is running at ${URL}"
echo "====================================="
echo ""

if [[ "$DEMO_MODE" == "true" ]]; then
  echo "  Demo mode: click any account on the"
  echo "  login page to sign in instantly."
else
  echo "  Visit ${URL} to create your admin"
  echo "  account and configure the hotline."
fi

echo ""
echo "  Logs:    ${COMPOSE_CMD} logs -f"
echo "  Stop:    ${COMPOSE_CMD} down"
echo "  Restart: ${COMPOSE_CMD} up -d"
echo ""
