// Barrel re-export of all API modules
// Consumers can import from '@/lib/api' as before — no import changes needed.

export * from './client'
export * from './config'
export * from './auth'
export * from './users'
export * from './calls'
export * from './notes'
export * from './shifts'
export * from './bans'
export * from './audit'
export * from './conversations'
export * from './reports'
export * from './contacts'
export * from './intakes'
export * from './blasts'
export * from './hubs'
export * from './settings'
export * from './files'
export * from './invites'
export * from './teams'
export * from './tags'
export * from './gdpr'
export * from './notifications'
export * from './demo'
